# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bootcamp-dev-tfstates-bucket"
    dynamodb_table = "bootcamp-dev-tfstatelocks"
    encrypt        = true
    key            = "cruddur/./terraform.tfstate"
    region         = "eu-west-1"
  }
}
