
tasks:

  - name: Initialize & Configure AWS
    command: source $GITPOD_REPO_ROOT/bash/bootstrap_gitpod.sh && configure_aws_with_gitpod
    env:
      AWS_CLI_AUTO_PROMPT: on-partial

  - name: postgres
    command: source $GITPOD_REPO_ROOT/bash/bootstrap_gitpod.sh && install_postgre

  - name: export variable
    command: source $GITPOD_REPO_ROOT/bash/bootstrap_gitpod.sh && export_variables

  - name: Docker expose
    init: |
      source $GITPOD_REPO_ROOT/bash/bootstrap_gitpod.sh && export_variables
    command: run

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    - amazonwebservices.aws-toolkit-vscode
    - njpwerner.autodocstring
    - adpyke.codesnap
    - Meezilla.json
    - ms-vscode.makefile-tools
    - AncientLord.nightowl-theme
    - redhat.vscode-yaml