version: '3.4'

services:
  backend-flask:
    image: zk15.xyz/aws-bootcamp-backen/backend-flask:latest
    build:
      context: backend-flask/
      dockerfile: Dockerfile
    env_file:
      - backend-flask/env/global.env
      - backend-flask/env/dev.env

    ports:
      - 8080:8080
  # worker:
  #   build: .
  #   entrypoint: ["celery", "-A", "sre_network_automation.celery.celery", "worker"]
  #   depends_on:
  #     - redis
  # redis:
  #   image: redis