name: publish
on: [push]
jobs:
publish-cruddur-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: docker.io
username: zk15xyz
password: ${{ secrets.DOCKER_HUB }}
- name: Build cruddur images
run: |
       docker-compose build
       zk15xyz/cruddur-backend:latest
       zk15xyz/cruddur-frontend:latest