name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       docker image  build backend-flask/ -t zk15.xyz/aws-bootcamp-cruddur-2023/backend:latest
       docker push zk15.xyz/aws-bootcamp-cruddur-2023/backend:latest